volumes:
  cache:
    driver: local
  db_data:
    driver: local
networks:
  app-network:
    driver: bridge
services:
  nginx:
    container_name: some-nginx
    image: nginx:stable
    profiles:
      - prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manga_app
    profiles:
      - prod
    networks:
      - app-network
    depends_on:
      - redis
      - db_pg
      - mongodb
    env_file:
      - .env
    expose:
      - 8080
  db_pg:
    image: postgres:15
    container_name: postgres
    profiles:
      - prod
      - dev
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
  redis:
    image: redis:latest
    container_name: some_redis
    profiles:
      - prod
      - dev
    depends_on:
      - db_pg
    networks:
      - app-network
    expose:
      - 6379
    ports:
      - 6379:6379
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    profiles:
      - prod
      - dev
    networks:
      - app-network
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    expose:
      - 27017
    ports:
      - 27017:27017
