volumes:
  cache:
    driver: local
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge

services:
  db_pg:
    image: postgres:15
    container_name: postgres
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./src/main/resources:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
  redis:
    image: redis:latest
    container_name: some_redis
    depends_on:
      - db_pg
    networks:
      - app-network
    ports:
      - 6379:6379