volumes:
  cache:
    driver: local
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge

services:
  nginx:
    container_name: some-nginx
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manga_app
    networks:
      - app-network
    depends_on:
      - redis
      - db_pg
    env_file:
      - .env
    expose:
      - 8080
  db_pg:
    image: postgres:15
    container_name: postgres
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./src/main/resources:/docker-entrypoint-initdb.d
    expose:
      - 5432
  redis:
    image: redis:latest
    container_name: some_redis
    depends_on:
      - db_pg
    networks:
      - app-network
    expose:
      - 6379