volumes:
  cache:
    driver: local
  db_data:
    driver: local
networks:
  app-network:
    driver: bridge
services:
  app:
    build:
      context: .
    container_name: manga_app
    networks:
      - app-network
    depends_on:
      - db_pg
      - redis
    env_file:
      - .env
    ports:
      - 8080

  db_pg:
    image: postgres:15
    container_name: postgres
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./src/main/resources:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
  redis:
    image: redis:7.2
    container_name: redis
    networks:
      - app-network
    restart: always
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
    volumes:
      - cache:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

