spring:
  config:
    import: file:.env[.properties]
  cache:
    type: redis
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      repositories:
        enabled: false
    mongodb:
      database: ${MONGO_DATABASE}
      password: ${MONGO_PASSWORD}
      username: ${MONGO_USERNAME}
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin
      authentication-database: admin
  docker:
    compose:
      profiles:
        active: dev
jwt:
  secret:
    access: '{"kty" : "oct", "k" : "hi7S5RX5ZRZooHA0RKGctZ-KtR9FoESgCnH-3BNg5XI"}'
    refresh: '{"kty" : "oct", "k" : "956PBFst1FguLr5irJD-aQ"}'
