spring:
  config:
    import: optional:file:.env[.properties]
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
jwt:
  secret:
    access: ${ACCESS_TOKEN}
    refresh: ${REFRESH_TOKEN}
logging:
  level:
    org.springframework.security: trace