spring:
  config:
    import: optional:file:.properties[.env]
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
jwt:
  secret:
    access: '{"kty" : "oct", "k" : "hi7S5RX5ZRZooHA0RKGctZ-KtR9FoESgCnH-3BNg5XI"}'
    refresh: '{"kty" : "oct", "k" : "956PBFst1FguLr5irJD-aQ"}'
logging:
  level:
    org.springframework.security: trace
